#*  All rights reserved.
#*/*
# * local_costmap_params_terrinet.yaml  (for ASPSI)
# *
# *  Created on: Dec 22, 2013. Last Modified by Ely Repiso on 2025 (migration to ros-Noetic and in the middle of 
# *  ros2- humble migration)
# *      Author: Initial code of the Robot alone AKP navigation is from Gonzalo Ferrer (2013).
# *      Author: Additions and new codes of ASPSI for people accompaniment code of Ely Repiso (from 2015 and currently).
# *
# *      License (for other authors that will not be the original ones): CC BY-NC-ND 4.0 
# *      (Attribution-NonCommercial-NoDerivatives 4.0 International)
# *        https://creativecommons.org/licenses/by-nc-nd/4.0/deed.en
# *
# *      This license does not allow other authors to modify or to take profit from these works. 
# *      Then, for modifications or derivative works, please contact ely.repiso@upc.edu to try to agree on 
# *  collaborations (for journals with other researchers, formal collaborations between UPC and companies, and so on).
# *
# *  Please to only use it cite: Repiso, Ely, Anaís Garrell, and Alberto Sanfeliu. "Adaptive social planner to accompany people in real-life dynamic environments." International Journal of Social Robotics 16.6 (2024): 1189-1221.
# */

#*  Redistribution and use in source and binary forms, without
#*  modification, are permitted provided that the following conditions
#*  are met:
#*
#*   * Redistributions of source code must retain the above copyright
#*     notice, this list of conditions and the following disclaimer.
#*   * Redistributions in binary form must reproduce the above
#*     copyright notice, this list of conditions and the following
#*     disclaimer in the documentation and/or other materials provided
#*     with the distribution.
#*   * Neither the name of the Willow Garage nor the names of its
#*     contributors may be used to endorse or promote products derived
#*     from this software without specific prior written permission.
#*   * Additionally, remember that the derivatives without collaboration 
#*     Of the original authors are prohibited
#*
#*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
#*  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
#*  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
#*  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
#*  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#*  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
#*  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#*  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
#*  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#*  POSSIBILITY OF SUCH DAMAGE.
#***********************************************************
local_costmap:
  publish_voxel_map: true
  global_frame:      /map
  robot_base_frame:  /base_frame
  update_frequency:  1.0
  publish_frequency: 1.0
  static_map:        false
  rolling_window:    true
  obstacle_range: 4.0
  raytrace_range: 4.0
  width:     8.0
  height:    8.0
  resolution: 0.3
  transform_tolerance: 1.0
  inflation_layer:
    inflation_radius: 1.0
    cost_scaling_factor: 3.0
  plugins:
  - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
