#*  All rights reserved.
#*/*
# * move_base_params.yaml  (for ASPSI)
# *
# *  Created on: Dec 22, 2013. Last Modified by Ely Repiso on 2025 (migration to ros-Noetic and in the middle of 
# *  ros2- humble migration)
# *      Author: Initial code of the Robot alone AKP navigation is from Gonzalo Ferrer (2013).
# *      Author: Additions and new codes of ASPSI for people accompaniment code of Ely Repiso (from 2015 and currently).
# *
# *      License (for other authors that will not be the original ones): CC BY-NC-ND 4.0 
# *      (Attribution-NonCommercial-NoDerivatives 4.0 International)
# *        https://creativecommons.org/licenses/by-nc-nd/4.0/deed.en
# *
# *      This license does not allow other authors to modify or to take profit from these works. 
# *      Then, for modifications or derivative works, please contact ely.repiso@upc.edu to try to agree on 
# *  collaborations (for journals with other researchers, formal collaborations between UPC and companies, and so on).
# *
# *  Please to only use it cite: Repiso, Ely, Anaís Garrell, and Alberto Sanfeliu. "Adaptive social planner to accompany people in real-life dynamic environments." International Journal of Social Robotics 16.6 (2024): 1189-1221.
# */

#*  Redistribution and use in source and binary forms, without
#*  modification, are permitted provided that the following conditions
#*  are met:
#*
#*   * Redistributions of source code must retain the above copyright
#*     notice, this list of conditions and the following disclaimer.
#*   * Redistributions in binary form must reproduce the above
#*     copyright notice, this list of conditions and the following
#*     disclaimer in the documentation and/or other materials provided
#*     with the distribution.
#*   * Neither the name of the Willow Garage nor the names of its
#*     contributors may be used to endorse or promote products derived
#*     from this software without specific prior written permission.
#*   * Additionally, remember that the derivatives without collaboration 
#*     Of the original authors are prohibited
#*
#*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
#*  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
#*  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
#*  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
#*  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#*  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
#*  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#*  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
#*  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#*  POSSIBILITY OF SUCH DAMAGE.
#***********************************************************
shutdown_costmaps: false

controller_frequency: 5.0
controller_patience: 5.0

planner_frequency: 0.0
planner_patience: 30.0

oscillation_timeout: 0.0 #infinite time
oscillation_distance: 0.2

recovery_behavior_enabled: false # true
clearing_rotation_allowed: false # true

base_local_planner: "iri_atr_akp_local_planner_companion/AkpLocalPlanner"
#alternatives: base_local_planner/TrajectoryPlannerROS, dwa_local_planner/DWAPlannerROS
base_global_planner: "navfn/NavfnROS"
#alternatives: navfn/NavfnROS, global_planner/GlobalPlanner, carrot_planner/CarrotPlanner

